from students import views 
from django.urls import path 

urlpatterns = [
    path("",views.home,name='home'),
    
    path("register/",views.RegisterStudent,name="registration"),
    path("Allstudents/",views.All_Student_Records,name="allstudents"),
    path("Fee/",views.FeeRecordTable,name="fee"),
    path("updatefee/<int:id>/",views.UpdateClassFee,name="updatefee"),
    path("AddFee/",views.AddFee,name="addfee"),
    path("UpdateRollNo/<int:id>/",views.UpdateRollNo,name="updaterollno"),
    path("AddFeeRecords/",views.FeeRecords,name="feerecords"),
    path("Feereport/",views.FeeRecReport,name="feereport"),
    path("FeeVouchers/",views.FeeVoucher,name="feevoucher"),
    path("Addteacher/",views.AddTeacher,name="addteacher"),
    path("studentdetail/",views.StudentDetail,name="studentdetail"),
    path("promotestudents/",views.PromoteStudents,name="promotestudents"),
    path("attendencestudents/",views.MarkAttendenceStudents,name="studentattendence"),
    path("attendancereport/",views.AttendanceReport,name="attendancereport"),
    path("attendancestatis/",views.AttendanceStatics,name='attendencestatics'),
    path("deletestudent/<int:id>/",views.deletestudent,name="deletestudent"),
    path("allteachers",views.AllTeachersRecords,name="allteachers"),
    path("deleteteacher/<slug:id>/",views.deleteteachers,name="deleteteacher"),
    path("updateFeerecord/<int:id>/",views.UpdateFeeRecord,name="updatefeerecord"),
    path("teacherdetails/",views.TeacherDetail,name="teacherdetail"),
    path("subjectlist/",views.Subject,name="subjects"),
    path("Addsubject/",views.AddSubject,name="addsubject"),
    path("percentagedetai/",views.StudentPercentage,name="percentagedetail"),
    path("accounts/",views.Accounts,name="accounts"),
    path("addexam/",views.AddExam,name="addexam"),
    path("updatesubject/<int:id>/",views.UpdateSubject,name="updatesubject"),
    path("showmarks/",views.ShowMarksRecord,name="marksrecord"),
    path("defaulterstudents/",views.CheckDefaulterstudent,name="defaultstudents"),
    path("Totalexpense/",views.PendingDues,name="pendingdues"),
    path("expenses/",views.ExpensesManagement,name="expenses"),
    path("updateexpense/<int:id>/",views.UpdateExpense,name="updateexpense"),
    path("Teacherattendance/",views.TeacherAttendanceModule,name="teacherattandance"),
    path("Teacherattandacereport/",views.TeacherAttenaceReport,name="teacherattandancreport"),
    path("Teacherattandancestatistics/",views.TeacherAttendancestatistics,name="teacherattandancestatistics"),
]
